### ISSUE TITLE
Need license notice in each files

### ISSUE THREAD

**Issue by atoato88** [kubernetes-sigs/kubebuilder-declarative-pattern#15]
Every file in this repo doesn't have license notice(Apache License, Version 2.0) at top.
It is needed for developing with this toolkit.

**Comment by atoato88** [comment]
This is non-functional topic, but important things, I think.

If this issue is reasonable for you, I'll create PR.
IMHO, this should be fix after #12.

**Comment by johnsonj** [comment]
Thanks @atoato88 - that'd be great. Agreed on sequencing.
