### ISSUE TITLE
We should start using versions

### ISSUE THREAD

**Issue by justinsb** [kubernetes-sigs/kubebuilder-declarative-pattern#174]
Per discussion in https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/169 we should probably have versioning in our library and maintain a release branch.

* This should make the library a little easier to consume
* By mirroring the version of controller-runtime (on which we have a hard dependency) we avoid having to define our own major/minor verision scheme.
* We can hopefully make issues like https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/169 easier to merge because we will have a clearer version policy (inherited from [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/master/VERSIONING.md) )

First steps are probably to start treating master as the 0.10 release.  If we want to we can also create a release-0.9 branch and tag 0.9.0, perhaps taking a snapshot from the period of relative inactivity a few months (as I've made/proposed some breaking changes since!)

**Comment by atoato88** [comment]
This PR has [`release-0.11` branch for v0.11.0.](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/208#issuecomment-1075074381)
When we would like to use v0.11.0, we write in `go.mod` which use this repository following:

```
require sigs.k8s.io/kubebuilder-declarative-pattern v0.11.0
```

I checked on test program which used v0.11.0, but `go mod tidy` failed with:
```
$ go mod tidy
go: downloading sigs.k8s.io/kubebuilder-declarative-pattern v0.11.0
example.com imports
        sigs.k8s.io/kubebuilder-declarative-pattern/pkg/patterns/declarative: reading sigs.k8s.io/kubebuilder-declarative-pattern/go.mod at revision v0.11.0: unknown revision v0.11.0
```

Do we need git tag named of `v0.11.0` ?
And I also refered [this page][1] on go.dev.

[1]: https://go.dev/ref/mod#vcs-version
