### ISSUE TITLE
If an object transform fails, status is never updated

### ISSUE THREAD

**Issue by tomasaschan** [kubernetes-sigs/kubebuilder-declarative-pattern#190]
**What happened**:
Consider a declarative reconciler set up like this:
```go
func (r *MyReconciler) setupReconciler(mgr ctrl.Manager) (declarative.LabelMaker, error) {
    // ...
    
    return watchLabels, r.Reconciler.Init(mgr, &myapiv1.MyResource{},
        // ...
        declarative.WithStatus(status.NewBasic(mgr.GetClient()),
        declarative.WithObjectTransform(myTransform),
    )
}

func myTransform(ctx context.Context, object declarative.DeclarativeObject, objects *manifest.Objects) error {
    return errors.New("demonstrate the issue")
}
```

**What you expected to happen**:
When reconciling this resource, I would expect the status to be updated with `.status.healthy: false`, and at least the error message, perhaps even more detail, exposed in `.status.errors` and/or `.status.phase`. Instead, the reconciliation seems to crash completely, requeue itself and not update anything. This leaves the resource hanging without a status, and with no feedback to the user other than the fact that it doesn't have a status...

**How to reproduce it (as minimally and precisely as possible)**:
1. Define a declarative controller and resource
2. Add a simple transform function, e.g. the one in the example above, that returns an `error`
3. Observe the reconciliation behavior

**Anything else we need to know?**:
I know there's a comment on `NewBasic` that it's been superseeded by `NewKstatusCheck`, but I haven't been able to get the latter to actually update the status even in the happy-path case.

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  λ kubectl version
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
  ```
- OS (e.g: `cat /etc/os-release`):
  ```
  λ cat /etc/os-release 
  NAME="Ubuntu"
  VERSION="20.04.3 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 20.04.3 LTS"
  VERSION_ID="20.04"
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  VERSION_CODENAME=focal
  UBUNTU_CODENAME=focal
  ```
- Kernel (e.g. `uname -a`):
  ```
  λ uname -a
  Linux sto-PC1238K4 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  ```
- Go version (e.g. `go version`):
  ```
  λ go version
  go version go1.17.3 linux/amd64
  ```

**Comment by atoato88** [comment]
In #199, any erros occured in reconciling are pass to [`Reconciled` function](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/199/files#diff-f4f154817e266917cf48c21f464818b16798c1d4e1170cee1af9804481f786f0R48).
We may be able to utilize those error informations for updating status said this issue, I think.
