### ISSUE TITLE
Complex manifest transformations

### ISSUE THREAD

**Issue by wscheep** [kubernetes-sigs/kubebuilder-declarative-pattern#196]
**What would you like to be added**: 
A way to modify Kustomize folder structures after loading them as raw manifests.

**Why is this needed**: 
We already have complex logic in kpt functions to do this and would like to re-use them. 
This ensures that local manifest rendering happens in exactly the same way as in the cluster.

**Details**:
Complex transformations are done by a kpt function that is taking a Kustomize folder structure as input and produces one as output. For this to work with the declarative pattern, I made the [following changes](https://github.com/wscheep/kubebuilder-declarative-pattern/pull/1/files):

* a new [rawManifestTransformation option](https://github.com/wscheep/kubebuilder-declarative-pattern/pull/1/files#diff-38244235b0a98d88ff98a6c49ceb1415c81d77487933745ec337d898553fcce1R72):
in: map[string]string (Kustomize structure)
out: map[string]string (Kustomize structure)  
Currently, this option enables us to trigger the internal kpt `Filter` function we use: `func Filter(items []*kyaml.RNode) ([]*kyaml.RNode, error)`.
See [this gist](https://gist.github.com/wscheep/1bfb75fae1b9d243381b2468bdcdfbd6) for the full function.

* A [workaround](https://github.com/wscheep/kubebuilder-declarative-pattern/pull/1/files#diff-91d9000f2817ed2698caf7b294e34ed1bc739bf60b7dc1af3136055b18741312R360) to make the final kustomize build happen on the root level.
If this is not set, the output of the kustomize build behavior is undeterministic,
as `manifestsObjects.Path` will contain one of the paths of the input manifests.
I can look into reproducing this behavior if needed.

Do you have thoughts on adding support for either all kinds of kpt functions or kpt Filter functions as options? As discussed before, one thing to figure out is the "docker-in-docker" problem.

Another related feature that would be nice is the ability to trigger the "kustomize build" before the conversion to objects happens. For our use case there is no need to modify objects before running "kustomize build" to get our final manifests. This way, there are no unnecessary conversions to/from objects.

Related issue: https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/182

**Comment by irvifa** [comment]
Hi @wscheep , I think it will be good if you put some example on how you'd like the structure and the format that you'd like to have in this issue as well as part of proposed design document.
