### ISSUE TITLE
No pruning with NewDirectApplier

### ISSUE THREAD

**Issue by wscheep** [kubernetes-sigs/kubebuilder-declarative-pattern#201]
**What happened**:
The `kubectl --prune` flag is set as `extraOpts` in [`reconciler.go`](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/pkg/patterns/declarative/reconciler.go#L236).

However, since the `NewDirectApplier` is used (https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/101), the prune option is not propagated to the `applyOpts.Prune` boolean of [`direct.go`](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/pkg/patterns/declarative/pkg/applier/direct.go#L80).

**What you expected to happen**:
The prune option to be propagated so that pruning happens as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Putting a breakpoint on [`direct.go#L80`](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/pkg/patterns/declarative/pkg/applier/direct.go#L80) clearly shows that the `Prune` flag is not set on the `applyOpts` object.

**Anything else we need to know?**:
There currently is also no support for the `--prune-whitelist` flag, which we need for our use case.
Happy to create a PR for this, but I think it's better to solve this issue first.

Is there a specific reason for keeping the old ExecApplier around?
If not, I guess the `ApplierOptions` from the library could be directly replaced by [`ApplyOptions`](https://github.com/kubernetes/kubectl/blob/8d3e8f9f6868315eb7204b7d511fac0abdc13e5c/pkg/cmd/apply/apply.go#L75) from the `k8s.io./kubectl` module.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`): macOS Big Sure 11.6.2
- Kernel (e.g. `uname -a`): 
```
Darwin C02YK2Z2JHD2 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,2 Darwin
```
- Go version (e.g. `go version`): `go version go1.17.6 darwin/amd64`
- Others:

**Comment by justinsb** [comment]
Thanks for figuring this out and for sending the PR - I'm going to look at why it isn't passing...

> Is there a specific reason for keeping the old ExecApplier around?
There's not a strong reason, other than avoiding breaking people.  However, extraArgs is pretty specific to the kubectl, and maybe we should replace that with more specific options instead.  (i.e. drop extraArgs, but expose Prune, ForceConflicts, Selector etc).

This feels like a great time to introduce stronger versioning into this library and maybe start cleaning up some of the older code.  Once we introduce versioning, we can then drop support for the exec applier at a version boundary (clearly announcing it).  (Versioning and clearer announcements there will also probably better let us find out if anyone wants to keep the execApplier!)

**Comment by wscheep** [comment]
Sounds good, let me know if there's anything I can do to help with introducing stronger versioning.

In the mean time, we've used a nicer workaround where we convert `ApplierOptions` into the latest [ApplyOptions](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/apply/apply.go) from the k8s.io./kubectl module.
I'll create a PR once the versioning is in place.

**Comment by xuzhenglun** [comment]
pruning seems still broken, because some attributes of applyOpts is nil.

To make pruning work normally, below attributes must be set before calling [applyOpts.Run()](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/pkg/patterns/declarative/pkg/applier/direct.go#L94).
```go
	applyOpts.Mapper = opt.RESTMapper
	applyOpts.DynamicClient, _ = dynamic.NewForConfig(opt.RESTConfig)
	applyOpts.DeleteOptions.CascadingStrategy = "Background"
	applyOpts.DeleteOptions.GracePeriod = -1
	applyOpts.PostProcessorFn = applyOpts.PrintAndPrunePostProcessor()
```

**Comment by atoato88** [comment]
Recently, some PRs related with `prune` functionality are created.
I think we should reopen this issue.

**Comment by xuzhenglun** [comment]
`DirectApplier` is implemented very tricky in the current code.  IMHO, some reason can blame that `k/kubectl` is lack of a good interface for other people to reuse it easily. 

To solve this issue, I have 3 ideas:
1. After 1.16, `ServerSide apply` is available, It allows client just send resources to `kube-apiserver`, and `kube-apiserver` will figure out how to deal with `apply` progress. The good side is this way can get rid of `k/kubectl` problems. But something bad is some function like `prune` is missing and we should implement it by self.
2. Reuse `k/kubectl` at a higher level, just like #211 did. But there are some codes which still have to be `copy & paste`. I know this is not a good way in practice, but I really did not find a way to reuse that code completely. Something detail can see in the discussion in that PR.
3. Or we can reuse `k/kubectl` in the highest level: binary level. It is exactly what `ExecApplier` did. So is there any way to enable it? I know that will introduce a binary dependency but also got a good side effect: users can use any version of `kubectl` if they want to. It can be a good thing because something in `k/kubectl` is version-related. such as the default value of `--prune-whitelist`.

**Comment by atoato88** [comment]
/reopen

@justinsb 
WDYT about comment above?

**Comment by xuzhenglun** [comment]
@justinsb

Any comment on this issue?

**Comment by xuzhenglun** [comment]
I believe that https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/217 fixes https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/201 too, and we can close this PR now.

WDYT @atoato88

**Comment by atoato88** [comment]
/close
Yes, as of now this issue is fixed, I think.
I close this.

**Comment by JeffLuoo** [comment]
Do we have tests that will cover the prune?

**Comment by atoato88** [comment]
We don't have cover tests to prune in DirectApplier.
We need more coverage on unit test for preventing some degrades. :sweat_smile:
