### ISSUE TITLE
question: How to handle cluster scoped resources?

### ISSUE THREAD

**Issue by killwing** [kubernetes-sigs/kubebuilder-declarative-pattern#234]
Currently cluster scoped resources can be created, but they're not removed when the declarative object is deleted because no ownerref. Is it expected that user should remove them manually?

**Comment by atoato88** [comment]
Current codebase don't set ownerref to those objects; [refer this comment](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/2072cf081b2e512b687c6bf152466646df1ac2c9/pkg/patterns/declarative/reconciler.go#L582-L584).
This was merged by #184
