### ISSUE TITLE
Support basic private registry for docker environments

### ISSUE THREAD

**Issue by johnsonj** [kubernetes-sigs/kubebuilder-declarative-pattern#35]
Provide a set of flags for addon operators that, when specified, rewrite the image names and add add a imagePullSecret to relevant PodSpecs.

Flags:
- `--private-registry=<my-repo>`
- `--image-pull-secret=<my-secret>`

**Comment by akulkapoor90** [comment]
hello Jeff,

In addition to the flag '--private-registry', what tag it would use to pull the image ?

does addons, support tags as well for private-registry or does it default to 'latest' ?

**Comment by brycecr** [comment]
Hey Akul,

It's going to use the tag you have specified in the image field. private-registry only overwrites the first two "/" delimited elements of the container location.

So, `gcr.io/akul/image:tag` with `--private-registry=priva.te/registry/location` would become `priva.te/registry/location/image:tag`, and `gcr.io/akul/kapoor/90/image:tag` would become `priva.te/registry/location/kapoor/90/image:tag`.

Note that `private-registry` doesn't touch the tag, I believe.

**Comment by johnsonj** [comment]
echoing @brycecr - it doesn't not touch tag. It'd be reasonably straightforward to mutate the tags in an [ObjectTransform](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/pkg/patterns/declarative/options.go#L87). That's how the private registry (repo/imagePullSecret) is implemented under the hood.

The thought behind not touching the tag or path beyond the first chunk is that if you're mirror images you would retain the structure and tag.
