### ISSUE TITLE
Mocks don't match current controller-runtime package

### ISSUE THREAD

**Issue by steeling** [kubernetes-sigs/kubebuilder-declarative-pattern#363]
**What happened**:

pkg/test/mocks/manager.go isn't up to date with the controller-runtime package marked in go.mod

**What you expected to happen**:

pkg/test/mocks/manager.go.Manager should implement the controller-runtime Manager interface that it is supposed to mock.

**How to reproduce it (as minimally and precisely as possible)**:

Attempt to use NewValidator

**Anything else we need to know?**:

`var _ manager.Manager = &Manager{}` line 48 in `pkg/test/mocks/manager.go` doesn't compile

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`):
- Others:

**Comment by steeling** [comment]
Looks like there's no linting or unit tests being run as a PR presubmit, aside from some KIND installation?
https://github.com/steeling/kubebuilder-declarative-pattern/blob/master/.github/workflows/main.yml

**Comment by tomasaschan** [comment]
@justinsb This is (at least part of) the problem I mentioned in controller-runtime compat.
