### ISSUE TITLE
Manage an Application Instance

### ISSUE THREAD

**Issue by johnsonj** [kubernetes-sigs/kubebuilder-declarative-pattern#5]
If a manifest includes an 'Application' we should be able to manage it (name, labels, GVKs, assembly phase, ...)

**Comment by Kashomon** [comment]
I would like to use Application resources as purely Metadata (info about the component). Would it possible to say, 'hey, I don't really want you to use my Application object'?

**Comment by johnsonj** [comment]
That makes sense. It's probably an option/transform so it will be opt-in to update it if it's there.
