### ISSUE TITLE
kustomize integration

### ISSUE THREAD

**Issue by annp1987** [kubernetes-sigs/kubebuilder-declarative-pattern#56]
Hi Everyone,

Currently, we can adding labels, changing namespace of manifest before apply them. But I'm not sure there is possible to manipulate manifest from `kustomize build` then apply it? Do you have any advice?

**Comment by johnsonj** [comment]
- [proposal for integration](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/57#issuecomment-559268407)

@annp1987 - Should we assign this bug to you?

**Comment by annp1987** [comment]
@johnsonj ,
Please assign this bug to me. Its my pleasure. :-)

**Comment by johnsonj** [comment]
Thanks @annp1987 ! Let me know if you have any questions/want an early review

**Comment by annp1987** [comment]
Thanks @johnsonj. Could you have a early review for kustomize integration at https://github.com/annp1987/kubebuilder-declarative-pattern/tree/intergrate_with_krusty?

**Comment by johnsonj** [comment]
Hey @annp1987 - sorry for the delay. Your change looks right on track. I don't have any major structural comments. I'm excited to see this one land!

This likely goes without saying, but you will need to keep track of the original filesystem paths and use them when you write to the in memory filesystem (`fSys.WriteFile`)

**Comment by annp1987** [comment]
Thanks @johnsonj. I've just create a PR. Could you take a look at it?

**Comment by johnsonj** [comment]
#66 added the initial support for this feature. We still need tests, documentation, and potentially more feature work for this to be closed out.

**Comment by johnsonj** [comment]
There's additional open issues highlighted in [@atoato88's comment](https://github.com/kubernetes-sigs/cluster-addons/pull/46#issuecomment-597415111)

**Comment by rajansandeep** [comment]
Adding further to [@atoato88's comment](https://github.com/kubernetes-sigs/cluster-addons/pull/46#issuecomment-597415111), if an operator has Kustomize enabled (for example CoreDNS-operator to include the `configMapGenerator`), we can just parse the final yaml built by the `kustomization.yaml`, instead of trying to parse all the files present in the version folder.

**Comment by johnsonj** [comment]
As it is today, the transformation process relies on being able to parse everything as YAML. For example, we have a private registry transform that will go patch all of the image registries. That's something we would like to keep.

We could make the file loading code more flexible: https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/bbf1fb2a4a9a5ab3cf14d3f5f3f06658ca6373f8/pkg/patterns/declarative/pkg/manifest/objects.go#L292

For example, we could change Objects to hold onto parsable Kubernetes types as it does today and keep the rest as plaintext/blobs.

```go
type Objects struct {
  Items []*Object
  Blobs [][]byte
}
```

**Comment by SomtochiAma** [comment]
@johnsonj how do we know when to change the Objects or when to keep as blobs?

**Comment by johnsonj** [comment]
@SomtochiAma If it can be parsed into an unstructured.Unstructured then it should be an Object. Otherwise, Blob

**Comment by SomtochiAma** [comment]
@rajansandeep Are you suggesting that we do [https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/56](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/56) before building the deployment objects?
