### ISSUE TITLE
Emit Reconciliation Metrics

### ISSUE THREAD

**Issue by johnsonj** [kubernetes-sigs/kubebuilder-declarative-pattern#65]
A user should be able to emit metrics on the Prometheus metrics endpoint. Metrics should be written to the [controller-runtime Prometheus Registry](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/metrics/registry.go#L23)

  The library should emit a metric for:

- P1: How many times in the last X seconds has reconciliation happened? How many times has it failed?  
    - Implement as two [CounterVec](https://godoc.org/github.com/prometheus/client_golang/prometheus#CounterVec) metrics. ReconcileCount, ReconcileFailedCount. Use labels that identify the object type (eg CoreDNS) and namespace/name. These can be directly defined in [reconciler.go](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/pkg/patterns/declarative/reconciler.go) 

- P2: How many objects (and what type) are being managed by the operator? 
    - Unclear how to implement this. A GaugeVec (with type/namespace/name labels) may work for this if the reconciler can keep track which types are created/destroyed.

/cc @annp1987

**Comment by vanou** [comment]
I'll take it.
/assign

**Comment by vanou** [comment]
I think this issue got closed.
/close

**Comment by atoato88** [comment]
Thank you to deal this.
I think so too.
/close
