### ISSUE TITLE
Add a Component loader

### ISSUE THREAD

**Issue by Kashomon** [kubernetes-sigs/kubebuilder-declarative-pattern#9]
I'd like to add a Component loader for components from https://github.com/GoogleCloudPlatform/k8s-cluster-bundle. Is that something you'd be interested in?

**Comment by johnsonj** [comment]
Yes, very interested. I'm happy to talk through any issues in integrating it if you have questions.

**Comment by Kashomon** [comment]
Presumably this would pull from in-cluster?

**Comment by Kashomon** [comment]
Alternatively, there could be component-fs loader and a component-remote loader. reference to https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/tree/master/pkg/patterns/addon/pkg/loaders

Seems like the objects accepted by the resolver in func (c *ManifestLoader) ResolveManifest(ctx context.Context, object runtime.Object) (string, error) {

**Comment by johnsonj** [comment]
Ultimately, I'd like to support the following (in no particular order):
- Raw manifests on disk (check!)
- Component via kubernetes API
- Component via URI (https://, file://)

In terms of integrating it into the Reconciler, you're spot on there. [Here's the spot](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/pkg/patterns/declarative/reconciler.go#L235) where the fs based loader is 'picked up'. I think we should select different loaders either via an Init(option..) or flag.

**Comment by Kashomon** [comment]
I think @BradfordMedeiros is going to take this up.

**Comment by Kashomon** [comment]
I think there's even a forth one that would be useful: Component on disk

**Comment by Kashomon** [comment]
(although maybe Component via URI encompasses component on disk)

**Comment by BradfordMedeiros** [comment]
Yea I will.  I'm poking around kubebuilder at the moment and trying to get a feel for it.

**Comment by BradfordMedeiros** [comment]
What's the usage for this repo? 
I'm looking into kubebuilder and it's not referenced statically from there, but I assume it's supposed to be used through generated code with this? 

What's the idea exactly?  I'm not following yet conceptually.  Is there an example usage? 
I'd also think we probably ought to both stabilize a bit before integrating, but still willing to do this once I understand the idea better.
