### ISSUE TITLE
How components installed by the operator work with autoscalers? 

### ISSUE THREAD

**Issue by erain** [kubernetes-sigs/kubebuilder-declarative-pattern#95]
This is more of a question than an issue. 

Operators may install and reconcile several components with own resource requests/limits. However, we may want these components to have different requests/limits depending on the size of the cluster. 

There are two options here:
1. Have some hooks in the framework, to do autoscaling from the operator.
2. Make the operator aware of the autoscalers, and don't reconcile if the resource requests/limits changed in those components. 

Could someone provide some guidance?

**Comment by dashpole** [comment]
cc @justinsb

**Comment by rajansandeep** [comment]
I'm not sure if this answers your question directly, but I do have a [Cluster Proportional Autoscaler](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler) installed using the CoreDNS operator, and the autoscaler is able to take control of the number of CoreDNS replicas without reconciling. 

Note: For this to work, I have avoided specifying the number of replicas in the CoreDNS deployment.

**Comment by johnsonj** [comment]
I think that is the right approach. 

The operators use apply semantics so as long as the field isn't set by the operator there will be no fight between the operator and an autoscaler. 

This breaks down if an operator wants a 'non-default default' (eg wants replicas: 3 - unless the autoscaler wants more/less). That could be implemented via a Patch, but I'm not sure if that's a hack.
